version: "3.2"

services:
  node-subtensor:
    container_name: node-subtensor
    image: opentensorfdn/subtensor:latest
    ports:
      - "9944:9944"
      - "30333:30333"
      - "9933:9933"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    command: bash -c "/usr/local/bin/node-subtensor --base-path /root/.local/share/node-subtensor/ --chain /subtensor/specs/nakamotoSpecRaw.json --rpc-external --ws-external --rpc-cors all --no-mdns --rpc-methods=Unsafe --ws-max-connections 1000 --in-peers 300 --out-peers 300 --pruning 10"
