version: "3.2"

services:
  dev:
    container_name: node-subtensor
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/node-subtensor
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-subtensor/.cargo
    volumes:
      - .:/var/www/node-subtensor
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-subtensor --chain nakamoto --rpc-external --ws-external --rpc-cors all --no-mdns --rpc-methods=Unsafe --ws-max-connections 10000"
